/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PoService } from "../po.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PoCreateInput } from "./PoCreateInput";
import { Po } from "./Po";
import { PoFindManyArgs } from "./PoFindManyArgs";
import { PoWhereUniqueInput } from "./PoWhereUniqueInput";
import { PoUpdateInput } from "./PoUpdateInput";
import { ProductionRecordFindManyArgs } from "../../productionRecord/base/ProductionRecordFindManyArgs";
import { ProductionRecord } from "../../productionRecord/base/ProductionRecord";
import { ProductionRecordWhereUniqueInput } from "../../productionRecord/base/ProductionRecordWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PoControllerBase {
  constructor(
    protected readonly service: PoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Po })
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPo(@common.Body() data: PoCreateInput): Promise<Po> {
    return await this.service.createPo({
      data: {
        ...data,

        sku: data.sku
          ? {
              connect: data.sku,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        numberField: true,

        sku: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Po] })
  @ApiNestedQuery(PoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pos(@common.Req() request: Request): Promise<Po[]> {
    const args = plainToClass(PoFindManyArgs, request.query);
    return this.service.pos({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        numberField: true,

        sku: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Po })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async po(@common.Param() params: PoWhereUniqueInput): Promise<Po | null> {
    const result = await this.service.po({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        numberField: true,

        sku: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Po })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePo(
    @common.Param() params: PoWhereUniqueInput,
    @common.Body() data: PoUpdateInput
  ): Promise<Po | null> {
    try {
      return await this.service.updatePo({
        where: params,
        data: {
          ...data,

          sku: data.sku
            ? {
                connect: data.sku,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          numberField: true,

          sku: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Po })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePo(
    @common.Param() params: PoWhereUniqueInput
  ): Promise<Po | null> {
    try {
      return await this.service.deletePo({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          numberField: true,

          sku: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/productionRecords")
  @ApiNestedQuery(ProductionRecordFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "read",
    possession: "any",
  })
  async findProductionRecords(
    @common.Req() request: Request,
    @common.Param() params: PoWhereUniqueInput
  ): Promise<ProductionRecord[]> {
    const query = plainToClass(ProductionRecordFindManyArgs, request.query);
    const results = await this.service.findProductionRecords(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        productionDateTime: true,
        expiryDate: true,
        batchNumber: true,

        sku: {
          select: {
            id: true,
          },
        },

        po: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/productionRecords")
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "update",
    possession: "any",
  })
  async connectProductionRecords(
    @common.Param() params: PoWhereUniqueInput,
    @common.Body() body: ProductionRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productionRecords: {
        connect: body,
      },
    };
    await this.service.updatePo({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/productionRecords")
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "update",
    possession: "any",
  })
  async updateProductionRecords(
    @common.Param() params: PoWhereUniqueInput,
    @common.Body() body: ProductionRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productionRecords: {
        set: body,
      },
    };
    await this.service.updatePo({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/productionRecords")
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "update",
    possession: "any",
  })
  async disconnectProductionRecords(
    @common.Param() params: PoWhereUniqueInput,
    @common.Body() body: ProductionRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productionRecords: {
        disconnect: body,
      },
    };
    await this.service.updatePo({
      where: params,
      data,
      select: { id: true },
    });
  }
}
