/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Po } from "./Po";
import { PoCountArgs } from "./PoCountArgs";
import { PoFindManyArgs } from "./PoFindManyArgs";
import { PoFindUniqueArgs } from "./PoFindUniqueArgs";
import { CreatePoArgs } from "./CreatePoArgs";
import { UpdatePoArgs } from "./UpdatePoArgs";
import { DeletePoArgs } from "./DeletePoArgs";
import { ProductionRecordFindManyArgs } from "../../productionRecord/base/ProductionRecordFindManyArgs";
import { ProductionRecord } from "../../productionRecord/base/ProductionRecord";
import { Sku } from "../../sku/base/Sku";
import { PoService } from "../po.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Po)
export class PoResolverBase {
  constructor(
    protected readonly service: PoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "read",
    possession: "any",
  })
  async _posMeta(@graphql.Args() args: PoCountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Po])
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "read",
    possession: "any",
  })
  async pos(@graphql.Args() args: PoFindManyArgs): Promise<Po[]> {
    return this.service.pos(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Po, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "read",
    possession: "own",
  })
  async po(@graphql.Args() args: PoFindUniqueArgs): Promise<Po | null> {
    const result = await this.service.po(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Po)
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "create",
    possession: "any",
  })
  async createPo(@graphql.Args() args: CreatePoArgs): Promise<Po> {
    return await this.service.createPo({
      ...args,
      data: {
        ...args.data,

        sku: args.data.sku
          ? {
              connect: args.data.sku,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Po)
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "update",
    possession: "any",
  })
  async updatePo(@graphql.Args() args: UpdatePoArgs): Promise<Po | null> {
    try {
      return await this.service.updatePo({
        ...args,
        data: {
          ...args.data,

          sku: args.data.sku
            ? {
                connect: args.data.sku,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Po)
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "delete",
    possession: "any",
  })
  async deletePo(@graphql.Args() args: DeletePoArgs): Promise<Po | null> {
    try {
      return await this.service.deletePo(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ProductionRecord], { name: "productionRecords" })
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "read",
    possession: "any",
  })
  async findProductionRecords(
    @graphql.Parent() parent: Po,
    @graphql.Args() args: ProductionRecordFindManyArgs
  ): Promise<ProductionRecord[]> {
    const results = await this.service.findProductionRecords(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Sku, {
    nullable: true,
    name: "sku",
  })
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "any",
  })
  async getSku(@graphql.Parent() parent: Po): Promise<Sku | null> {
    const result = await this.service.getSku(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
