/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Po as PrismaPo,
  ProductionRecord as PrismaProductionRecord,
  Sku as PrismaSku,
} from "@prisma/client";

export class PoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PoCountArgs, "select">): Promise<number> {
    return this.prisma.po.count(args);
  }

  async pos(args: Prisma.PoFindManyArgs): Promise<PrismaPo[]> {
    return this.prisma.po.findMany(args);
  }
  async po(args: Prisma.PoFindUniqueArgs): Promise<PrismaPo | null> {
    return this.prisma.po.findUnique(args);
  }
  async createPo(args: Prisma.PoCreateArgs): Promise<PrismaPo> {
    return this.prisma.po.create(args);
  }
  async updatePo(args: Prisma.PoUpdateArgs): Promise<PrismaPo> {
    return this.prisma.po.update(args);
  }
  async deletePo(args: Prisma.PoDeleteArgs): Promise<PrismaPo> {
    return this.prisma.po.delete(args);
  }

  async findProductionRecords(
    parentId: string,
    args: Prisma.ProductionRecordFindManyArgs
  ): Promise<PrismaProductionRecord[]> {
    return this.prisma.po
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .productionRecords(args);
  }

  async getSku(parentId: string): Promise<PrismaSku | null> {
    return this.prisma.po
      .findUnique({
        where: { id: parentId },
      })
      .sku();
  }
}
