/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ProductionRecord } from "./ProductionRecord";
import { ProductionRecordCountArgs } from "./ProductionRecordCountArgs";
import { ProductionRecordFindManyArgs } from "./ProductionRecordFindManyArgs";
import { ProductionRecordFindUniqueArgs } from "./ProductionRecordFindUniqueArgs";
import { CreateProductionRecordArgs } from "./CreateProductionRecordArgs";
import { UpdateProductionRecordArgs } from "./UpdateProductionRecordArgs";
import { DeleteProductionRecordArgs } from "./DeleteProductionRecordArgs";
import { Sku } from "../../sku/base/Sku";
import { Po } from "../../po/base/Po";
import { ProductionRecordService } from "../productionRecord.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ProductionRecord)
export class ProductionRecordResolverBase {
  constructor(
    protected readonly service: ProductionRecordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "read",
    possession: "any",
  })
  async _productionRecordsMeta(
    @graphql.Args() args: ProductionRecordCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ProductionRecord])
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "read",
    possession: "any",
  })
  async productionRecords(
    @graphql.Args() args: ProductionRecordFindManyArgs
  ): Promise<ProductionRecord[]> {
    return this.service.productionRecords(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ProductionRecord, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "read",
    possession: "own",
  })
  async productionRecord(
    @graphql.Args() args: ProductionRecordFindUniqueArgs
  ): Promise<ProductionRecord | null> {
    const result = await this.service.productionRecord(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ProductionRecord)
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "create",
    possession: "any",
  })
  async createProductionRecord(
    @graphql.Args() args: CreateProductionRecordArgs
  ): Promise<ProductionRecord> {
    return await this.service.createProductionRecord({
      ...args,
      data: {
        ...args.data,

        sku: args.data.sku
          ? {
              connect: args.data.sku,
            }
          : undefined,

        po: args.data.po
          ? {
              connect: args.data.po,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ProductionRecord)
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "update",
    possession: "any",
  })
  async updateProductionRecord(
    @graphql.Args() args: UpdateProductionRecordArgs
  ): Promise<ProductionRecord | null> {
    try {
      return await this.service.updateProductionRecord({
        ...args,
        data: {
          ...args.data,

          sku: args.data.sku
            ? {
                connect: args.data.sku,
              }
            : undefined,

          po: args.data.po
            ? {
                connect: args.data.po,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ProductionRecord)
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "delete",
    possession: "any",
  })
  async deleteProductionRecord(
    @graphql.Args() args: DeleteProductionRecordArgs
  ): Promise<ProductionRecord | null> {
    try {
      return await this.service.deleteProductionRecord(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Sku, {
    nullable: true,
    name: "sku",
  })
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "any",
  })
  async getSku(
    @graphql.Parent() parent: ProductionRecord
  ): Promise<Sku | null> {
    const result = await this.service.getSku(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Po, {
    nullable: true,
    name: "po",
  })
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "read",
    possession: "any",
  })
  async getPo(@graphql.Parent() parent: ProductionRecord): Promise<Po | null> {
    const result = await this.service.getPo(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
