/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ProductionRecord as PrismaProductionRecord,
  Sku as PrismaSku,
  Po as PrismaPo,
} from "@prisma/client";

export class ProductionRecordServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ProductionRecordCountArgs, "select">
  ): Promise<number> {
    return this.prisma.productionRecord.count(args);
  }

  async productionRecords(
    args: Prisma.ProductionRecordFindManyArgs
  ): Promise<PrismaProductionRecord[]> {
    return this.prisma.productionRecord.findMany(args);
  }
  async productionRecord(
    args: Prisma.ProductionRecordFindUniqueArgs
  ): Promise<PrismaProductionRecord | null> {
    return this.prisma.productionRecord.findUnique(args);
  }
  async createProductionRecord(
    args: Prisma.ProductionRecordCreateArgs
  ): Promise<PrismaProductionRecord> {
    return this.prisma.productionRecord.create(args);
  }
  async updateProductionRecord(
    args: Prisma.ProductionRecordUpdateArgs
  ): Promise<PrismaProductionRecord> {
    return this.prisma.productionRecord.update(args);
  }
  async deleteProductionRecord(
    args: Prisma.ProductionRecordDeleteArgs
  ): Promise<PrismaProductionRecord> {
    return this.prisma.productionRecord.delete(args);
  }

  async getSku(parentId: string): Promise<PrismaSku | null> {
    return this.prisma.productionRecord
      .findUnique({
        where: { id: parentId },
      })
      .sku();
  }

  async getPo(parentId: string): Promise<PrismaPo | null> {
    return this.prisma.productionRecord
      .findUnique({
        where: { id: parentId },
      })
      .po();
  }
}
