/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProductionRecordService } from "../productionRecord.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductionRecordCreateInput } from "./ProductionRecordCreateInput";
import { ProductionRecord } from "./ProductionRecord";
import { ProductionRecordFindManyArgs } from "./ProductionRecordFindManyArgs";
import { ProductionRecordWhereUniqueInput } from "./ProductionRecordWhereUniqueInput";
import { ProductionRecordUpdateInput } from "./ProductionRecordUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductionRecordControllerBase {
  constructor(
    protected readonly service: ProductionRecordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProductionRecord })
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProductionRecord(
    @common.Body() data: ProductionRecordCreateInput
  ): Promise<ProductionRecord> {
    return await this.service.createProductionRecord({
      data: {
        ...data,

        sku: data.sku
          ? {
              connect: data.sku,
            }
          : undefined,

        po: data.po
          ? {
              connect: data.po,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        productionDateTime: true,
        expiryDate: true,
        batchNumber: true,

        sku: {
          select: {
            id: true,
          },
        },

        po: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProductionRecord] })
  @ApiNestedQuery(ProductionRecordFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async productionRecords(
    @common.Req() request: Request
  ): Promise<ProductionRecord[]> {
    const args = plainToClass(ProductionRecordFindManyArgs, request.query);
    return this.service.productionRecords({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        productionDateTime: true,
        expiryDate: true,
        batchNumber: true,

        sku: {
          select: {
            id: true,
          },
        },

        po: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProductionRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async productionRecord(
    @common.Param() params: ProductionRecordWhereUniqueInput
  ): Promise<ProductionRecord | null> {
    const result = await this.service.productionRecord({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        productionDateTime: true,
        expiryDate: true,
        batchNumber: true,

        sku: {
          select: {
            id: true,
          },
        },

        po: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProductionRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProductionRecord(
    @common.Param() params: ProductionRecordWhereUniqueInput,
    @common.Body() data: ProductionRecordUpdateInput
  ): Promise<ProductionRecord | null> {
    try {
      return await this.service.updateProductionRecord({
        where: params,
        data: {
          ...data,

          sku: data.sku
            ? {
                connect: data.sku,
              }
            : undefined,

          po: data.po
            ? {
                connect: data.po,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          productionDateTime: true,
          expiryDate: true,
          batchNumber: true,

          sku: {
            select: {
              id: true,
            },
          },

          po: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProductionRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProductionRecord(
    @common.Param() params: ProductionRecordWhereUniqueInput
  ): Promise<ProductionRecord | null> {
    try {
      return await this.service.deleteProductionRecord({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          productionDateTime: true,
          expiryDate: true,
          batchNumber: true,

          sku: {
            select: {
              id: true,
            },
          },

          po: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
