/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Sku } from "./Sku";
import { SkuCountArgs } from "./SkuCountArgs";
import { SkuFindManyArgs } from "./SkuFindManyArgs";
import { SkuFindUniqueArgs } from "./SkuFindUniqueArgs";
import { CreateSkuArgs } from "./CreateSkuArgs";
import { UpdateSkuArgs } from "./UpdateSkuArgs";
import { DeleteSkuArgs } from "./DeleteSkuArgs";
import { PoFindManyArgs } from "../../po/base/PoFindManyArgs";
import { Po } from "../../po/base/Po";
import { ProductionRecordFindManyArgs } from "../../productionRecord/base/ProductionRecordFindManyArgs";
import { ProductionRecord } from "../../productionRecord/base/ProductionRecord";
import { SkuService } from "../sku.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Sku)
export class SkuResolverBase {
  constructor(
    protected readonly service: SkuService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "any",
  })
  async _skusMeta(
    @graphql.Args() args: SkuCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Sku])
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "any",
  })
  async skus(@graphql.Args() args: SkuFindManyArgs): Promise<Sku[]> {
    return this.service.skus(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Sku, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "own",
  })
  async sku(@graphql.Args() args: SkuFindUniqueArgs): Promise<Sku | null> {
    const result = await this.service.sku(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Sku)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "create",
    possession: "any",
  })
  async createSku(@graphql.Args() args: CreateSkuArgs): Promise<Sku> {
    return await this.service.createSku({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Sku)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "update",
    possession: "any",
  })
  async updateSku(@graphql.Args() args: UpdateSkuArgs): Promise<Sku | null> {
    try {
      return await this.service.updateSku({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Sku)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "delete",
    possession: "any",
  })
  async deleteSku(@graphql.Args() args: DeleteSkuArgs): Promise<Sku | null> {
    try {
      return await this.service.deleteSku(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Po], { name: "pos" })
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "read",
    possession: "any",
  })
  async findPos(
    @graphql.Parent() parent: Sku,
    @graphql.Args() args: PoFindManyArgs
  ): Promise<Po[]> {
    const results = await this.service.findPos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ProductionRecord], { name: "productionRecords" })
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "read",
    possession: "any",
  })
  async findProductionRecords(
    @graphql.Parent() parent: Sku,
    @graphql.Args() args: ProductionRecordFindManyArgs
  ): Promise<ProductionRecord[]> {
    const results = await this.service.findProductionRecords(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
