/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Sku as PrismaSku,
  Po as PrismaPo,
  ProductionRecord as PrismaProductionRecord,
} from "@prisma/client";

export class SkuServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SkuCountArgs, "select">): Promise<number> {
    return this.prisma.sku.count(args);
  }

  async skus(args: Prisma.SkuFindManyArgs): Promise<PrismaSku[]> {
    return this.prisma.sku.findMany(args);
  }
  async sku(args: Prisma.SkuFindUniqueArgs): Promise<PrismaSku | null> {
    return this.prisma.sku.findUnique(args);
  }
  async createSku(args: Prisma.SkuCreateArgs): Promise<PrismaSku> {
    return this.prisma.sku.create(args);
  }
  async updateSku(args: Prisma.SkuUpdateArgs): Promise<PrismaSku> {
    return this.prisma.sku.update(args);
  }
  async deleteSku(args: Prisma.SkuDeleteArgs): Promise<PrismaSku> {
    return this.prisma.sku.delete(args);
  }

  async findPos(
    parentId: string,
    args: Prisma.PoFindManyArgs
  ): Promise<PrismaPo[]> {
    return this.prisma.sku
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .pos(args);
  }

  async findProductionRecords(
    parentId: string,
    args: Prisma.ProductionRecordFindManyArgs
  ): Promise<PrismaProductionRecord[]> {
    return this.prisma.sku
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .productionRecords(args);
  }
}
