/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SkuService } from "../sku.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SkuCreateInput } from "./SkuCreateInput";
import { Sku } from "./Sku";
import { SkuFindManyArgs } from "./SkuFindManyArgs";
import { SkuWhereUniqueInput } from "./SkuWhereUniqueInput";
import { SkuUpdateInput } from "./SkuUpdateInput";
import { PoFindManyArgs } from "../../po/base/PoFindManyArgs";
import { Po } from "../../po/base/Po";
import { PoWhereUniqueInput } from "../../po/base/PoWhereUniqueInput";
import { ProductionRecordFindManyArgs } from "../../productionRecord/base/ProductionRecordFindManyArgs";
import { ProductionRecord } from "../../productionRecord/base/ProductionRecord";
import { ProductionRecordWhereUniqueInput } from "../../productionRecord/base/ProductionRecordWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SkuControllerBase {
  constructor(
    protected readonly service: SkuService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sku })
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSku(@common.Body() data: SkuCreateInput): Promise<Sku> {
    return await this.service.createSku({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        shelfLife: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Sku] })
  @ApiNestedQuery(SkuFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async skus(@common.Req() request: Request): Promise<Sku[]> {
    const args = plainToClass(SkuFindManyArgs, request.query);
    return this.service.skus({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        shelfLife: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sku })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sku(@common.Param() params: SkuWhereUniqueInput): Promise<Sku | null> {
    const result = await this.service.sku({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        shelfLife: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sku })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSku(
    @common.Param() params: SkuWhereUniqueInput,
    @common.Body() data: SkuUpdateInput
  ): Promise<Sku | null> {
    try {
      return await this.service.updateSku({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          shelfLife: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sku })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSku(
    @common.Param() params: SkuWhereUniqueInput
  ): Promise<Sku | null> {
    try {
      return await this.service.deleteSku({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          shelfLife: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/pos")
  @ApiNestedQuery(PoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Po",
    action: "read",
    possession: "any",
  })
  async findPos(
    @common.Req() request: Request,
    @common.Param() params: SkuWhereUniqueInput
  ): Promise<Po[]> {
    const query = plainToClass(PoFindManyArgs, request.query);
    const results = await this.service.findPos(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        numberField: true,

        sku: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/pos")
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "update",
    possession: "any",
  })
  async connectPos(
    @common.Param() params: SkuWhereUniqueInput,
    @common.Body() body: PoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pos: {
        connect: body,
      },
    };
    await this.service.updateSku({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/pos")
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "update",
    possession: "any",
  })
  async updatePos(
    @common.Param() params: SkuWhereUniqueInput,
    @common.Body() body: PoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pos: {
        set: body,
      },
    };
    await this.service.updateSku({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/pos")
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "update",
    possession: "any",
  })
  async disconnectPos(
    @common.Param() params: SkuWhereUniqueInput,
    @common.Body() body: PoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pos: {
        disconnect: body,
      },
    };
    await this.service.updateSku({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/productionRecords")
  @ApiNestedQuery(ProductionRecordFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductionRecord",
    action: "read",
    possession: "any",
  })
  async findProductionRecords(
    @common.Req() request: Request,
    @common.Param() params: SkuWhereUniqueInput
  ): Promise<ProductionRecord[]> {
    const query = plainToClass(ProductionRecordFindManyArgs, request.query);
    const results = await this.service.findProductionRecords(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        productionDateTime: true,
        expiryDate: true,
        batchNumber: true,

        sku: {
          select: {
            id: true,
          },
        },

        po: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/productionRecords")
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "update",
    possession: "any",
  })
  async connectProductionRecords(
    @common.Param() params: SkuWhereUniqueInput,
    @common.Body() body: ProductionRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productionRecords: {
        connect: body,
      },
    };
    await this.service.updateSku({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/productionRecords")
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "update",
    possession: "any",
  })
  async updateProductionRecords(
    @common.Param() params: SkuWhereUniqueInput,
    @common.Body() body: ProductionRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productionRecords: {
        set: body,
      },
    };
    await this.service.updateSku({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/productionRecords")
  @nestAccessControl.UseRoles({
    resource: "Sku",
    action: "update",
    possession: "any",
  })
  async disconnectProductionRecords(
    @common.Param() params: SkuWhereUniqueInput,
    @common.Body() body: ProductionRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productionRecords: {
        disconnect: body,
      },
    };
    await this.service.updateSku({
      where: params,
      data,
      select: { id: true },
    });
  }
}
