/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { UserInput } from "./UserInput";
import { UserInputCountArgs } from "./UserInputCountArgs";
import { UserInputFindManyArgs } from "./UserInputFindManyArgs";
import { UserInputFindUniqueArgs } from "./UserInputFindUniqueArgs";
import { CreateUserInputArgs } from "./CreateUserInputArgs";
import { UpdateUserInputArgs } from "./UpdateUserInputArgs";
import { DeleteUserInputArgs } from "./DeleteUserInputArgs";
import { UserInputService } from "../userInput.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserInput)
export class UserInputResolverBase {
  constructor(
    protected readonly service: UserInputService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "read",
    possession: "any",
  })
  async _userInputsMeta(
    @graphql.Args() args: UserInputCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserInput])
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "read",
    possession: "any",
  })
  async userInputs(
    @graphql.Args() args: UserInputFindManyArgs
  ): Promise<UserInput[]> {
    return this.service.userInputs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserInput, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "read",
    possession: "own",
  })
  async userInput(
    @graphql.Args() args: UserInputFindUniqueArgs
  ): Promise<UserInput | null> {
    const result = await this.service.userInput(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserInput)
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "create",
    possession: "any",
  })
  async createUserInput(
    @graphql.Args() args: CreateUserInputArgs
  ): Promise<UserInput> {
    return await this.service.createUserInput({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserInput)
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "update",
    possession: "any",
  })
  async updateUserInput(
    @graphql.Args() args: UpdateUserInputArgs
  ): Promise<UserInput | null> {
    try {
      return await this.service.updateUserInput({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserInput)
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "delete",
    possession: "any",
  })
  async deleteUserInput(
    @graphql.Args() args: DeleteUserInputArgs
  ): Promise<UserInput | null> {
    try {
      return await this.service.deleteUserInput(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
