/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserInputService } from "../userInput.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserInputCreateInput } from "./UserInputCreateInput";
import { UserInput } from "./UserInput";
import { UserInputFindManyArgs } from "./UserInputFindManyArgs";
import { UserInputWhereUniqueInput } from "./UserInputWhereUniqueInput";
import { UserInputUpdateInput } from "./UserInputUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserInputControllerBase {
  constructor(
    protected readonly service: UserInputService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserInput })
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserInput(
    @common.Body() data: UserInputCreateInput
  ): Promise<UserInput> {
    return await this.service.createUserInput({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        poNumber: true,
        runningSku: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserInput] })
  @ApiNestedQuery(UserInputFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userInputs(@common.Req() request: Request): Promise<UserInput[]> {
    const args = plainToClass(UserInputFindManyArgs, request.query);
    return this.service.userInputs({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        poNumber: true,
        runningSku: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userInput(
    @common.Param() params: UserInputWhereUniqueInput
  ): Promise<UserInput | null> {
    const result = await this.service.userInput({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        poNumber: true,
        runningSku: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserInput(
    @common.Param() params: UserInputWhereUniqueInput,
    @common.Body() data: UserInputUpdateInput
  ): Promise<UserInput | null> {
    try {
      return await this.service.updateUserInput({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          poNumber: true,
          runningSku: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserInput",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserInput(
    @common.Param() params: UserInputWhereUniqueInput
  ): Promise<UserInput | null> {
    try {
      return await this.service.deleteUserInput({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          poNumber: true,
          runningSku: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
